// client/src/LandingPage.js
import React from "react";
import styles from "./styles/landingpage.module.css"; // Import the CSS module

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-black flex flex-col">
      <div>
        <h1
          className={`text-5xl font-bold text-green-500 justify-left mb-8 text-left ${styles.indent}`}
        >
          The RWA tokenization protocol
        </h1>
        <p className="text-xl text-green-300 mb-8"></p>
      </div>

      <section className="container mx-auto px-4 md:px-0 mt-16">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="text-green-300">
            <h2 className="text-3xl font-bold mb-4">
              Tokenization of Real Assets
            </h2>
            <p className="mb-4">
              Tokenized real world assets on ArchonX provide investors a low-fee
              access to several types of yield bearing assets such as real
              estate, farmland, debt and invoices. Tokens represent structured
              debt instruments issued by ArchonX or audited partner companies.
              These debt instruments have a preferred claim on free cash flows
              generated by the underlying asset.
            </p>
            <p>
              Tokenization is the process of converting real-world assets into
              digital tokens that can be bought, sold, or traded on blockchain
              networks. By tokenizing real assets, we can improve the liquidity,
              transparency, and accessibility of these markets.
            </p>
          </div>
          <div className="text-center">
            <figure>
              <img
                src="https://via.placeholder.com/300" // Replace with the URL of your desired image
                alt="Tokenization illustration"
                className="rounded-md mx-auto"
              />
              <figcaption className="text-green-300 mt-4">
                Tokenization of real assets on the blockchain
              </figcaption>
            </figure>
          </div>
        </div>
      </section>

      <section className="container mx-auto px-4 md:px-0 mt-16">
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <div className="text-center">
            <figure>
              <img
                src="https://via.placeholder.com/150" // Replace with the URL of your desired image
                alt="Investors"
                className="rounded-md mx-auto"
              />
              <figcaption className="text-green-300 mt-4">Investors</figcaption>
            </figure>
          </div>
          <div className="text-center">
            <figure>
              <img
                src="https://via.placeholder.com/150" // Replace with the URL of your desired image
                alt="Tokenization illustration"
                className="rounded-md mx-auto"
              />
              <figcaption className="text-green-300 mt-4">
                Developers/Issuers
              </figcaption>
            </figure>
          </div>
          <div className="text-center">
            <figure>
              <img
                src="https://via.placeholder.com/150" // Replace with the URL of your desired image
                alt="Tokenization illustration"
                className="rounded-md mx-auto"
              />
              <figcaption className="text-green-300 mt-4">Users</figcaption>
            </figure>
          </div>
        </div>
      </section>

      <section className="container mx-auto px-4 md:px-0 mt-16">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <div className="text-center">
            <figure>
              <img
                src="https://via.placeholder.com/200" // Replace with the URL of your desired image
                alt="Tokenization illustration"
                className="rounded-md mx-auto"
              />
            </figure>
          </div>

          <div className="text-green-300">
            <h2 className="text-3xl font-bold mb-4">Why invest in xTokens</h2>
            <p className="mb-4">
              Benefit from unique on-chain financial instruments backed by real
              assets.
            </p>
          </div>
        </div>
      </section>

      <div>
        <h2>Hedge against inflation</h2>
        <p>
          archonX tokens provide exposure to real assets that gain in price as
          inflation rages on. Diversify your portfolio Liquid digital income
          Diversify your portfolio
        </p>
      </div>
    </div>
  );
};

export default LandingPage;
