// client/src/LandingPage.js
import React from "react";

const LandingPage = () => {
  return (
    <div className="min-h-screen bg-black flex flex-col justify-center items-center">
      <div className="text-left">
        <h1 className="text-5xl font-bold text-green-500 mb-8">
          The RWA tokenization protocol
        </h1>
        <p className="text-xl text-green-300 mb-8">
          Tokenized real world assets on ArchonX provide investors a low-fee
          access to several types of yield bearing assets such as real estate,
          farmland, debt and invoices. Tokens represent structured debt
          instruments issued by ArchonX or audited partner companies. These debt
          instruments have a preferred claim on free cash flows generated by the
          underlying asset.
        </p>
      </div>
    </div>
  );
};

export default LandingPage;
